# Generated by Django 5.2.17 on 2026-10-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("station", models.CharField(max_length=32)),
                ("station_name", models.CharField(max_length=40)),
                (
                    "start_min",
                    models.PositiveIntegerField(help_text="минута от начала смены"),
                ),
                (
                    "clock",
                    models.CharField(help_text="время по часам, ЧЧ:ММ", max_length=5),
                ),
                ("duration_min", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=80)),
                ("equipment", models.CharField(blank=True, max_length=40)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "высокий"),
                            ("medium", "средний"),
                            ("low", "низкий"),
                        ],
                        default="low",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "новый"),
                            ("work", "в работе"),
                            ("closed", "закрыт"),
                        ],
                        default="new",
                        max_length=8,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "руководитель смены"),
                            ("ml", "прогноз ML"),
                        ],
                        default="manual",
                        max_length=8,
                    ),
                ),
                ("impact", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
    ]
